[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[build.environment]
NIXPACKS_PKGS = "opus libopus0 ffmpeg" 